name: Android
on: [push, pull_request]

permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:

    - name: 下载源码
      uses: actions/checkout@v1

    - name: 配置JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: 下载submodule源码
      run: mv -f .gitmodules_github .gitmodules && git submodule sync && git submodule update --init

    - name: 赋予gradlew文件可执行权限
      run: chmod +x ./Android/gradlew

    - name: 编译
      run: cd Android && ./gradlew build

    - name: 设置环境变量
      run: |
        echo "BRANCH=$(echo ${GITHUB_REF#refs/heads/} | tr -s "/\?%*:|\"<>" "_")" >> $GITHUB_ENV  
        echo "BRANCH2=$(echo ${GITHUB_REF#refs/heads/} )" >> $GITHUB_ENV    
        echo "DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV

    - name: 打包二进制
      id: upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.workflow }}_${{ env.BRANCH }}_${{ env.DATE }}
        path: Android/app/build/outputs/apk/debug/*
        if-no-files-found: error
        retention-days: 90

    - name: 发布到 GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: |
          Android/app/build/outputs/apk/debug/*
        make_latest: true
        draft: false
        prerelease: false