name: macOS

on: [push, pull_request]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1

    - name: 下载submodule源码
      run: mv -f .gitmodules_github .gitmodules && git submodule sync && git submodule update --init

    - name: 配置 vcpkg
      uses: lukka/run-vcpkg@v7
      with:
        vcpkgDirectory: '${{github.workspace}}/vcpkg'
        vcpkgTriplet: arm64-osx
        # 2024.06.01
        vcpkgGitCommitId: '47364fbc300756f64f7876b549d9422d5f3ec0d3'
        vcpkgArguments: 'openssl libsrtp[openssl] usrsctp'

    - name: 编译
      uses: lukka/run-cmake@v3
      with:
        useVcpkgToolchainFile: true
        buildDirectory: '${{github.workspace}}/build'
        cmakeAppendedArgs: ''
        cmakeBuildType: 'Release'

    - name: 设置环境变量
      run: |
        echo "BRANCH=$(echo ${GITHUB_REF#refs/heads/} | tr -s "/\?%*:|\"<>" "_")" >> $GITHUB_ENV  
        echo "BRANCH2=$(echo ${GITHUB_REF#refs/heads/} )" >> $GITHUB_ENV    
        echo "DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV

    - name: 打包二进制
      id: upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.workflow }}_${{ env.BRANCH }}_${{ env.DATE }}
        path: release/*
        if-no-files-found: error
        retention-days: 90